apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: new
  name: deploy-novo
  namespace: virtualizacao
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: new
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - new
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: nginx:1.17.6-alpine
        name: container1
        resources: {}
      - image: kubernetes/pause
        name: container2
        resources: {}

status: {}
